### ISSUE TITLE
Example json with pre-auth with Apache

### ISSUE THREAD

**Issue by roostercactus** [fboender/scriptform#5]
Hi, this is a great program that I'm evaluating for use at work.  I have most everything working but I could use some help with setting up pre-authentication from Apache.  In my json file I'm using the allowed_user parameter to limit who can see the form.  Based on the wiki page, it says that when you use pre-auth it doesn't verify the password and assumes the username is correct.  So in the json file do you still need to list out the users in the 'users' section with a hash?  Or just the line for allowed_users?  If I only specify the allowed_user, it never shows me the form.  If I specify the users, it keeps prompting me for the internal user password...not the Apache pre-auth user.  I do have the header setup (as far as I can tell) in Apache.  How do I verify that scriptform is getting the user from Apache correctly?  I see this in my Apache logs:  

`192.168.0.100 - my.apache.account [26/Apr/2017:16:27:05 -0400] "GET /scriptform/ HTTP/1.1" 200 2943`

and  in my json file I have this:  

{
    "title": "Some Title",
    "forms": [
        {
            "name": "some_name",
            "title": "do some stuff",
            "description": "stuff",
            "script": "job_stuff.sh",
            "allowed_users": ["my.apache.account"],
            "run_as": "root",
            "fields": []
        }
    ]
}

Here's my apache config:  

RequestHeader set REMOTE_USER %{REMOTE_USER}s

  Redirect permanent /scriptform /scriptform/
  ProxyPass /scriptform/ http://localhost:8000/
  ProxyPassReverse /scriptform/ http://localhost:8000/

<Location /scriptform>
    SSLRequireSSL 
    Options None 
    AllowOverride None 
    Order allow,deny 
    Allow from all
    Require ldap-attribute gidNumber="7012"
    AuthzLDAPAuthoritative on
    AuthType Basic
    Require valid-user
    AuthName "scriptform with AD creds...username is first.last"
    AuthBasicProvider ldap
    AuthLDAPURL "ldaps://someAD.domain.com/OU=something,OU=somthing,dc=domain,dc=com?sAMAccountName?sub?(objectClass=*)"
    AuthLDAPBindDN "CN=bindacct,OU=accounts,OU=account,DC=domain,DC=com"
    AuthLDAPBindPassword "myADpass"
  </Location>
</VirtualHost>

Thanks for any help.

**Comment by fboender** [comment]
Hi roostercactus!

I suspect that you are using a packaged version of Scriptform (one of the official releases)? The Pre-auth functionality is very new and isn't included in the official release yet. This would explain the problems you're having with it.

I still have a few other features I want to add before I'm releasing v1.3, but in the meantime I've made you 1.3-pre packages you can use until the real v1.3 is out. They should be just as stable as v1.2. You  can find them here: https://electricmonk.nl/public/

You can simply upgrade your current version by installing one of the 1.3-pre packages as mentioned in the README. (dpkg -i ..., etc).

 If you're actually running from the master branch instead of from a package, please let me know because that would mean there's a bug it.

>  So in the json file do you still need to list out the users in the 'users' section with a hash? Or just the line for allowed_users?

All you have to do is add a "allowed_users" to the form definition. Those users will be allowed to see and use the form. The whole "users" section can be ommitted.

I hope this helps and feel free to ask further if need be!

**Comment by roostercactus** [comment]
Hi, thanks for the quick reply.  Sorry I should have said what version I was using.  I was using the 1.2 release (https://github.com/fboender/scriptform/releases/download/1.2/scriptform-1.2.tar.gz).  The pre-version 1.3 works fine and as expected.  Thanks again, love this program!

**Comment by fboender** [comment]
Hey Roostercactus!

FYI, version 1.3 is now officially out! You can get it from the releases page: https://github.com/fboender/scriptform/releases/tag/1.3

With kind regards,

Ferry
